### PR TITLE
A few design improvements and simplifications

### PR DESCRIPTION
**Pull request by meteorsw**
I have made a few improvements to this project. Each changeset is described in the meteorsw_improvements.rst file which I have written and added to this repository.

### CODE REVIEW

**Comment by Wolf-at-SO** [comment]
Quite impressive speed :)
Do all your improvements maintain the existing API?

The checks failed - as I understand it - due to a problem with downloading the Python nightly. Any idea what to do?

**Comment by meteorsw** [comment]
The only build which fails is the one using python-nightly. As far as I can tell, this appears to be some problem with the project's setup.py being somehow incompatible with python-nightly distutils, and is unrelated to my changes. I personally don't use python-nightly builds, so I don't know how to fix.

**Comment by Wolf-at-SO** [comment]
@meteorsw  I see, thanks for the explanation. Wouldn't it be reasonable to adjust the Travis settings to leave out the python nightly [like this](https://github.com/Wolf-at-SO/MIDIUtil/commit/e23d2d7fee7f0793fc0a9c1121404122c90151d7) - or does this seem too naive to you?

**Comment by meteorsw** [comment]
Presumably the original author included python nightly in his Travis CI intentionally. Hiding the problem by just removing it doesn't seem polite. I think it would be good to wait for the original author to look at this pull request, maybe he will have some thoughts on the problem with python nightly CI.

**Comment by MarkCWirt** [comment]
Hey guys --sorry I've been a bit absent: started a new job a few weeks ago and have been pretty busy!

I'll try to take a gander at the request this weekend. I'm all for improving things (some of this code is pretty old!) but I'd like to understand the failures. IIRC the nightly builds are "the shape of python to come", so I'd like to figure out what's going on there...

Thanks.

--M

**Comment by MarkCWirt** [comment]
I think the travis nightly builds are broken -- the software unmodified no longer compiles cleanly, and I think the issue may be one at Travis CI. I'm going to remove the nightly build requirement for the time being, as it doesn't seem to be doing anything.

I'll evaluate this pull request in that light.

**Comment by MarkCWirt** [comment]
OK, looked over the pull request. It's very nice! I wrote a lot of this code almost 10 years ago, and as you can see it was kind of messy.

(I actually prefer having quarter notes as the basic time as opposed to ticks, but that's the way I use the code.)

Anyway, I merged the pull request, but as it's a pretty major change, I decided to push it to `develop`, as opposed to `master`.

**Comment by MarkCWirt** [comment]
Merged into develop

**Pull request closed without merging**
